/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TextArtGeneratorRouteImport } from './routes/text-art-generator'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SymbolLibraryRouteImport } from './routes/symbol-library'
import { Route as StylishSignatureGeneratorRouteImport } from './routes/stylish-signature-generator'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NicknameDecoratorRouteImport } from './routes/nickname-decorator'
import { Route as InvisibleCharacterRouteImport } from './routes/invisible-character'
import { Route as FancyTextGeneratorRouteImport } from './routes/fancy-text-generator'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AestheticTextGeneratorRouteImport } from './routes/aesthetic-text-generator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TextArtGeneratorRoute = TextArtGeneratorRouteImport.update({
  id: '/text-art-generator',
  path: '/text-art-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SymbolLibraryRoute = SymbolLibraryRouteImport.update({
  id: '/symbol-library',
  path: '/symbol-library',
  getParentRoute: () => rootRouteImport,
} as any)
const StylishSignatureGeneratorRoute =
  StylishSignatureGeneratorRouteImport.update({
    id: '/stylish-signature-generator',
    path: '/stylish-signature-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NicknameDecoratorRoute = NicknameDecoratorRouteImport.update({
  id: '/nickname-decorator',
  path: '/nickname-decorator',
  getParentRoute: () => rootRouteImport,
} as any)
const InvisibleCharacterRoute = InvisibleCharacterRouteImport.update({
  id: '/invisible-character',
  path: '/invisible-character',
  getParentRoute: () => rootRouteImport,
} as any)
const FancyTextGeneratorRoute = FancyTextGeneratorRouteImport.update({
  id: '/fancy-text-generator',
  path: '/fancy-text-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AestheticTextGeneratorRoute = AestheticTextGeneratorRouteImport.update({
  id: '/aesthetic-text-generator',
  path: '/aesthetic-text-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aesthetic-text-generator': typeof AestheticTextGeneratorRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/fancy-text-generator': typeof FancyTextGeneratorRoute
  '/invisible-character': typeof InvisibleCharacterRoute
  '/nickname-decorator': typeof NicknameDecoratorRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stylish-signature-generator': typeof StylishSignatureGeneratorRoute
  '/symbol-library': typeof SymbolLibraryRoute
  '/terms': typeof TermsRoute
  '/text-art-generator': typeof TextArtGeneratorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aesthetic-text-generator': typeof AestheticTextGeneratorRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/fancy-text-generator': typeof FancyTextGeneratorRoute
  '/invisible-character': typeof InvisibleCharacterRoute
  '/nickname-decorator': typeof NicknameDecoratorRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stylish-signature-generator': typeof StylishSignatureGeneratorRoute
  '/symbol-library': typeof SymbolLibraryRoute
  '/terms': typeof TermsRoute
  '/text-art-generator': typeof TextArtGeneratorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aesthetic-text-generator': typeof AestheticTextGeneratorRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/fancy-text-generator': typeof FancyTextGeneratorRoute
  '/invisible-character': typeof InvisibleCharacterRoute
  '/nickname-decorator': typeof NicknameDecoratorRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stylish-signature-generator': typeof StylishSignatureGeneratorRoute
  '/symbol-library': typeof SymbolLibraryRoute
  '/terms': typeof TermsRoute
  '/text-art-generator': typeof TextArtGeneratorRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/aesthetic-text-generator'
    | '/blog'
    | '/contact'
    | '/disclaimer'
    | '/fancy-text-generator'
    | '/invisible-character'
    | '/nickname-decorator'
    | '/privacy'
    | '/sitemap.xml'
    | '/stylish-signature-generator'
    | '/symbol-library'
    | '/terms'
    | '/text-art-generator'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aesthetic-text-generator'
    | '/contact'
    | '/disclaimer'
    | '/fancy-text-generator'
    | '/invisible-character'
    | '/nickname-decorator'
    | '/privacy'
    | '/sitemap.xml'
    | '/stylish-signature-generator'
    | '/symbol-library'
    | '/terms'
    | '/text-art-generator'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/aesthetic-text-generator'
    | '/blog'
    | '/contact'
    | '/disclaimer'
    | '/fancy-text-generator'
    | '/invisible-character'
    | '/nickname-decorator'
    | '/privacy'
    | '/sitemap.xml'
    | '/stylish-signature-generator'
    | '/symbol-library'
    | '/terms'
    | '/text-art-generator'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AestheticTextGeneratorRoute: typeof AestheticTextGeneratorRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FancyTextGeneratorRoute: typeof FancyTextGeneratorRoute
  InvisibleCharacterRoute: typeof InvisibleCharacterRoute
  NicknameDecoratorRoute: typeof NicknameDecoratorRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StylishSignatureGeneratorRoute: typeof StylishSignatureGeneratorRoute
  SymbolLibraryRoute: typeof SymbolLibraryRoute
  TermsRoute: typeof TermsRoute
  TextArtGeneratorRoute: typeof TextArtGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/text-art-generator': {
      id: '/text-art-generator'
      path: '/text-art-generator'
      fullPath: '/text-art-generator'
      preLoaderRoute: typeof TextArtGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symbol-library': {
      id: '/symbol-library'
      path: '/symbol-library'
      fullPath: '/symbol-library'
      preLoaderRoute: typeof SymbolLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylish-signature-generator': {
      id: '/stylish-signature-generator'
      path: '/stylish-signature-generator'
      fullPath: '/stylish-signature-generator'
      preLoaderRoute: typeof StylishSignatureGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nickname-decorator': {
      id: '/nickname-decorator'
      path: '/nickname-decorator'
      fullPath: '/nickname-decorator'
      preLoaderRoute: typeof NicknameDecoratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invisible-character': {
      id: '/invisible-character'
      path: '/invisible-character'
      fullPath: '/invisible-character'
      preLoaderRoute: typeof InvisibleCharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fancy-text-generator': {
      id: '/fancy-text-generator'
      path: '/fancy-text-generator'
      fullPath: '/fancy-text-generator'
      preLoaderRoute: typeof FancyTextGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aesthetic-text-generator': {
      id: '/aesthetic-text-generator'
      path: '/aesthetic-text-generator'
      fullPath: '/aesthetic-text-generator'
      preLoaderRoute: typeof AestheticTextGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AestheticTextGeneratorRoute: AestheticTextGeneratorRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  FancyTextGeneratorRoute: FancyTextGeneratorRoute,
  InvisibleCharacterRoute: InvisibleCharacterRoute,
  NicknameDecoratorRoute: NicknameDecoratorRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StylishSignatureGeneratorRoute: StylishSignatureGeneratorRoute,
  SymbolLibraryRoute: SymbolLibraryRoute,
  TermsRoute: TermsRoute,
  TextArtGeneratorRoute: TextArtGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
